### ISSUE TITLE
Add command line arguments to specify configuration

### ISSUE THREAD

**Issue by r-julien-bataille** [rakutentech/docpub#21]
Currently DocPub is being configured with environment variables. Need to replace it with convenient command line arguments.
Command line arguments should override environment variables and configuration file.

Minimum required arguments (if one is specified, the two others must be specified):
username: string, name of ZenDesk user from whose name docs would be published
apiToken: string, ZenDesk API token of the user
url: string, zendesk root URL

**Comment by corycaywood** [comment]
For the CLI arguments, an additional option can be added to use `password` instead of `apiToken`. 

This will allow users who have the correct permissions to upload without needing to generate an API token.

**Comment by ADHER** [comment]
Note : The "light agents" can create and publish documents in Zendesk. But they don't have access to tokens. Therefore CLI arguments are an excellent feature.

**Comment by SwinX** [comment]
Resolved in #30
