### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by SwinX** [rakutentech/docpub#6]
Currently `DocPub` is being configured with environment variables. Need to replace it with convenient config.
Config name should be `.docpub.config`
Config should be located in a folder submitted to publish
Minimum required fields:
- `username`: `string`, name of ZenDesk user from whose name docs would be published
- `apiToken`: `string`, ZenDesk API token of the user
- `url`: `string`, zendesk root URL

**Comment by SwinX** [comment]
Do we need to support redefining this options with env variables or CLI args?

**Comment by corycaywood** [comment]
`.docpub.config` doesn't need to be a hidden file.

**Comment by ADHER** [comment]
From Scott:
I suggest there be a required name for it and have the repo's gitignore set to ignore it. Then include a sample one with some instructions on copying it to the "real" config.

I agree, so there is no accidental upload with credentials. Obliviously this apply to devs.

**Comment by SwinX** [comment]
Additional requirements for the config:

- Possibility to override each config option with CLI arg 
- Possibility to override each config option with ENV variable
- Priorities: CLI arg > ENV variable > Config entry
